/* Generated By:JavaCC: Do not edit this line. CompilerConstants.java */
package com.C0Compiler.JavaCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF_TO = 5;
  /** RegularExpression Id. */
  int INT_TO = 6;
  /** RegularExpression Id. */
  int VOID_TO = 7;
  /** RegularExpression Id. */
  int ELSE_TO = 8;
  /** RegularExpression Id. */
  int MAIN_TO = 9;
  /** RegularExpression Id. */
  int WHILE_TO = 10;
  /** RegularExpression Id. */
  int SCANF_TO = 11;
  /** RegularExpression Id. */
  int PRINTF_TO = 12;
  /** RegularExpression Id. */
  int RETURN_TO = 13;
  /** RegularExpression Id. */
  int ID_TO = 14;
  /** RegularExpression Id. */
  int NUM_TO = 15;
  /** RegularExpression Id. */
  int DOUHAO_TO = 16;
  /** RegularExpression Id. */
  int FENHAO_TO = 17;
  /** RegularExpression Id. */
  int JIAHAO_TO = 18;
  /** RegularExpression Id. */
  int JIANHAO_TO = 19;
  /** RegularExpression Id. */
  int CHENGHAO_TO = 20;
  /** RegularExpression Id. */
  int CHUHAO_TO = 21;
  /** RegularExpression Id. */
  int DENGHAO_TO = 22;
  /** RegularExpression Id. */
  int LBRACE_TO = 23;
  /** RegularExpression Id. */
  int RBRACE_TO = 24;
  /** RegularExpression Id. */
  int LPARENTHESES_TO = 25;
  /** RegularExpression Id. */
  int RPARENTHESES_TO = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"if\"",
    "\"int\"",
    "\"void\"",
    "\"else\"",
    "\"main\"",
    "\"while\"",
    "\"scanf\"",
    "\"printf\"",
    "\"return\"",
    "<ID_TO>",
    "<NUM_TO>",
    "\",\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
  };

}
