/* Generated By:JavaCC: Do not edit this line. Compiler.java */
package com.C0Compiler.JavaCC;
import com.C0Compiler.JavaCC.ExError;
import com.C0Compiler.JavaCC.MiddleCodeItem;
import com.C0Compiler.JavaCC.SymbolItem;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Scanner;

public class Compiler implements CompilerConstants {
    //主函数的入口
    public static void main(String path) throws ParseException {
        try {
            InputStream inputstream = new FileInputStream(path);
            Compiler parser = new Compiler(inputstream);
            parser.procedure();
        }catch (Exception e){
            System.err.println(e);
        }
    }
    //全局空间单词�?
    public static ArrayList<SymbolItem> listMain = new ArrayList();
    //分程序空间单词表
    public static ArrayList<SymbolItem> listPart = new ArrayList();
    //超前调用单词�?
    public static ArrayList<SymbolItem> listOutstrip = new ArrayList();
    //中间代码�?
    public static ArrayList<MiddleCodeItem> middleCodeList = new ArrayList();
    //返回标志
    public static boolean returnFlag = false;
    public static int returnFlagType = 0;

    public static ArrayList<MiddleCodeItem> getMiddleCodeList()
    {
        return middleCodeList;
    }

    /** 
     * 向单词表中添加单�?
     * @param type 0-全局空间 1-函数内空�?
     */
    public static void addSymbolList(Token t,int type){
        SymbolItem symbolItem = new SymbolItem(SymbolItem.SymbolType.intSym);
        symbolItem.setName(t.image);
        symbolItem.setLevel(type);
        if(type==0){
            //全局空间的单词表
            for(int i=0;i<listMain.size();i++){
                if(listMain.get(i).getName().equals(symbolItem.getName())){
                    //单词表已经存�?
                    ExError.ShowErrMsg(3,"The variable "+symbolItem.getName()+" has already been defined!--0");
                }
            }
            listMain.add(symbolItem);
        }else{
            //函数内的单词�?
            int lastFunction = 0;
            for(int i=listPart.size()-1;i>-1;i--){
                if(listPart.get(i).getType()==SymbolItem.SymbolType.functionSym){
                    lastFunction = i;
                    break;
                }
            }
            for(int i=lastFunction;i<listPart.size();i++){
                if(listPart.get(i).getName().equals(symbolItem.getName())){
                    ExError.ShowErrMsg(3,"The variable "+symbolItem.getName()+" has already been defined!--1");
                }
            }
            listPart.add(symbolItem);
        }
    }
    /** 
     * 请求初始化空�?
     * @param type 0-全局空间 1-函数内空�?
     */
    public static void askForSpace(int type){
        if(type==0){
            MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.INT,0,listMain.size());
            middleCodeList.add(item);
            callMainFunction();
        }else{
            int newVarSize = 0;
            for(int i=0;i<listPart.size();i++){
                if(listPart.get(i).getType()==SymbolItem.SymbolType.intSym){
                    newVarSize++;
                }else{
                    newVarSize = 0;
                }
            }
            MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.INT,0,newVarSize);
            middleCodeList.add(item);
        }
    }
    /**
     * 全局变量定义完调用主函数
     */
    public static void callMainFunction(){
        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.CAL,0,0);
        middleCodeList.add(item);
        MiddleCodeItem item2 = new MiddleCodeItem(MiddleCodeItem.CodeType.RET,0,0);
        middleCodeList.add(item2);
    }
    /**
     * 输出中间代码�?
     */
    public static void outPutMiddleCodeList(){
        System.out.println("\u6d93\ue162\u68ff\u6d60\uff47\u721c\u951b\u6b55n");
        for(int i=0;i<middleCodeList.size();i++){
            MiddleCodeItem m = middleCodeList.get(i);
            System.out.println(i+"\u005ct"+m.toOutString());
        }
    }
    /**
     * 输出分程序列�?
     */
    public static void outPutListPart(){
        System.out.println("\u9351\u82a5\u669f\u9352\u6944\u3003\u951b\u6b55n");
        for(int i=0;i<listPart.size();i++){
            System.out.println(i+"\u005ct"+listPart.get(i).toString());
        }
        System.out.println("\u74d2\u546d\u58a0\u748b\u51aa\u6564\u9428\u52eb\u56b1\u93c1\u7668n");
        //超前调用函数未定�?
        for(int i=0;i<listOutstrip.size();i++){
            String name = listOutstrip.get(i).getName();
            ExError.ShowErrMsg(4,"The function "+name+" was not defined");
        }
    }
    /**
     * 输出目标代码
     */
    public static void outPutGoalCode(){
        FileOutputStream out;
        try{
            out = new FileOutputStream("D:\u005c\u005cout.txt");
            for(int i=0;i<middleCodeList.size();i++){
                MiddleCodeItem m = middleCodeList.get(i);
                out.write(m.toString().getBytes("GBK"));
                out.write("\u005cr\u005cn".getBytes("GBK"));
            }
            out.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    /** 
     * 添加自定义函�? 
     * 添加后要�?查是否超前调�?
     * @param type 1-return int          0-return void
     */
    public static void addPartFunction(Token t,int type){
        SymbolItem symbolItem = new SymbolItem(SymbolItem.SymbolType.functionSym);
        symbolItem.setName(t.image);
        symbolItem.setReturnType(type);
        symbolItem.setAdr(middleCodeList.size());
        listPart.add(symbolItem);
        //查看是否为超前调用函�?
        for(int i=0;i<listOutstrip.size();i++){
            if(listOutstrip.get(i).getName().equals(t.image)){
                SymbolItem sym = listOutstrip.get(i);
                middleCodeList.get(sym.getAdr()).arg1 = middleCodeList.size();
                listOutstrip.remove(i);
                i--;
            }
        }
    }

    /**
     * 在单词表中寻找变�?
     * @param type 0-取变�? 1-赋�??
     */
    public static void getVariableById(Token t, int type){
        String id = t.image;
        int lastFunction = 0;
        //判断是否为是那个函数中的变量
        for(int i=listPart.size()-1;i>-1;i--){
            if(listPart.get(i).getType()==SymbolItem.SymbolType.functionSym){
                lastFunction = i;
                break;
            }
        }
        //查找变量名找�? true 未找�? false
        int relative = 1;   //相对地址
        boolean isFind = false;
        for (int i=lastFunction;i<listPart.size();i++) {
            if(listPart.get(i).getType()==SymbolItem.SymbolType.intSym){
                relative++;
                if(listPart.get(i).getName().equals(id)){
                    isFind = true;
                    break;
                }
            }
        }
        if(isFind){
            //找到后判断是取�?�还是赋�?
            if(type==0){
                MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.LOD,1,relative);
                middleCodeList.add(item);
            }else{
                MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.STO,1,relative);
                middleCodeList.add(item);
            }
        }else{
            //未找�? 可能为全�?变量
            relative = -1;
            for(int i=0;i<listMain.size();i++){
                relative++;
                if(listMain.get(i).getName().equals(id)){
                    if(type==0){
                        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.LOD,0,relative);
                        middleCodeList.add(item);
                    }else{
                        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.STO,0,relative);
                        middleCodeList.add(item);
                    }
                    return;
                }
            }
            //未定�?
            ExError.ShowErrMsg(3,"The variable "+id+" was not defined");
        }
    }
    /**
     * 在单词表中寻找函�?
     */
    public static void getFunctionById(Token t){
        //函数调用
        for(int i=0;i<listPart.size();i++){
            SymbolItem item = listPart.get(i);
            if(item.getType()==SymbolItem.SymbolType.functionSym){
                if(item.getName().equals(t.image)){
                    MiddleCodeItem middleCodeItem = new MiddleCodeItem(MiddleCodeItem.CodeType.CAL,0,item.getAdr());
                    middleCodeList.add(middleCodeItem);
                    return;
                }
            }
        }
        //如果单词表中没有该函数，则进行超前调�?
        SymbolItem symbolItem = new SymbolItem(SymbolItem.SymbolType.functionSym);
        symbolItem.setName(t.image);
        symbolItem.setAdr(middleCodeList.size());
        listOutstrip.add(symbolItem);
        //因为不确定调用位置，先设置为0
        MiddleCodeItem middleCodeItem = new MiddleCodeItem(MiddleCodeItem.CodeType.CAL,0,0);
        middleCodeList.add(middleCodeItem);
    }

/** 程序入口abcc */
  static final public void procedure() throws ParseException {
    if (jj_2_1(2)) {
      VarDefinition_CC(0);
    } else {
      ;
    }
    label_1:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_1;
      }
      FunctionDefinition_CC();
    }
    MainFunction_CC();
    jj_consume_token(0);
        //程序结束 输出中间代码、分程序、目标代�?
        outPutMiddleCodeList();
        outPutListPart();
        outPutGoalCode();
  }

/** 变量定义部分. type 全局/函数*/
  static final public void VarDefinition_CC(int type) throws ParseException {
    Token s;
    jj_consume_token(INT_TO);
    s = jj_consume_token(ID_TO);
        addSymbolList(s,type);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DOUHAO_TO:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_2;
      }
      jj_consume_token(DOUHAO_TO);
      s = jj_consume_token(ID_TO);
        addSymbolList(s,type);
    }
    jj_consume_token(FENHAO_TO);
        askForSpace(type);
  }

/** 自定义函数定义部�?. */
  static final public void FunctionDefinition_CC() throws ParseException {
    Token s;
    int type;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT_TO:
      jj_consume_token(INT_TO);
        type = 1;
        //returnFlagType = 1;

      s = jj_consume_token(ID_TO);
      break;
    case VOID_TO:
      jj_consume_token(VOID_TO);
        type = 0;
        //returnFlagType = 0;

      s = jj_consume_token(ID_TO);
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(LPARENTHESES_TO);
    jj_consume_token(RPARENTHESES_TO);
        addPartFunction(s,type);
    PartProgram_CC();
  }

/** 主函数部�? */
  static final public void MainFunction_CC() throws ParseException {
    Token s;
    jj_consume_token(VOID_TO);
    s = jj_consume_token(MAIN_TO);
    jj_consume_token(LPARENTHESES_TO);
    jj_consume_token(RPARENTHESES_TO);
        returnFlagType = 0;
        int mainAddress = middleCodeList.size();
        middleCodeList.get(1).arg1 = mainAddress;   //index0为定义变�?1为主函数调用
        addPartFunction(s,0);
    PartProgram_CC();
  }

/** 
 * 分程�?
 * 如果分程序没有返回�?�，则自动补上返回�??
 */
  static final public void PartProgram_CC() throws ParseException {
    jj_consume_token(LBRACE_TO);
        returnFlag = false;
    if (jj_2_3(2)) {
      VarDefinition_CC(1);
    } else {
      ;
    }
    WordList_CC();
    jj_consume_token(RBRACE_TO);
        if(!returnFlag){
            MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.RET,0,0);
            middleCodeList.add(item);
        }
  }

/** 语句序列 */
  static final public void WordList_CC() throws ParseException {
    Word_CC();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF_TO:
      case WHILE_TO:
      case SCANF_TO:
      case PRINTF_TO:
      case RETURN_TO:
      case ID_TO:
      case FENHAO_TO:
      case LBRACE_TO:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      Word_CC();
    }
  }

/** 语句 */
  static final public void Word_CC() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IF_TO:
      IfWord_CC();
      break;
    case WHILE_TO:
      ForWord_CC();
      break;
    case LBRACE_TO:
      jj_consume_token(LBRACE_TO);
      WordList_CC();
      jj_consume_token(RBRACE_TO);
      break;
    default:
      jj_la1[3] = jj_gen;
      if (jj_2_4(2)) {
        DefinitionFunctionCallWord_CC();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case ID_TO:
          EvaluateWord_CC();
          break;
        case RETURN_TO:
          ReturnWord_CC();
                    returnFlag=true;
          break;
        case SCANF_TO:
          ScanfWord_CC();
          break;
        case PRINTF_TO:
          PrintfWord_CC();
          break;
        case FENHAO_TO:
          jj_consume_token(FENHAO_TO);
          break;
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

/** 条件语句 */
  static final public void IfWord_CC() throws ParseException {
    int jpcAdress;
    int jmpAdress;
    jj_consume_token(IF_TO);
    jj_consume_token(LPARENTHESES_TO);
    Expression_CC();
        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.JPC,0,0);
        middleCodeList.add(item);
        jpcAdress = middleCodeList.size()-1;    //JPC的位�?

    jj_consume_token(RPARENTHESES_TO);
    Word_CC();
        MiddleCodeItem item2 = new MiddleCodeItem(MiddleCodeItem.CodeType.JMP,0,middleCodeList.size()+1);
        middleCodeList.add(item2);
        middleCodeList.get(jpcAdress).arg1 = middleCodeList.size();     //跳到JMP的位�?
        jmpAdress = middleCodeList.size()-1;
    if (jj_2_5(2)) {
      jj_consume_token(ELSE_TO);
      Word_CC();
        middleCodeList.get(jmpAdress).arg1 = middleCodeList.size();
    } else {
      ;
    }
  }

/** 循环语句 */
  static final public void ForWord_CC() throws ParseException {
    int whileBegin;
    int whileEnd;
    jj_consume_token(WHILE_TO);
        whileBegin = middleCodeList.size();
    jj_consume_token(LPARENTHESES_TO);
    Expression_CC();
        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.JPC,0,whileBegin);
        middleCodeList.add(item);
    jj_consume_token(RPARENTHESES_TO);
    Word_CC();
        MiddleCodeItem item2 = new MiddleCodeItem(MiddleCodeItem.CodeType.JMP,0,whileBegin);
        middleCodeList.add(item2);
        whileEnd = middleCodeList.size();
        middleCodeList.get(whileBegin+1).arg1 = whileEnd;
  }

/** 自定义函数调用语�? */
  static final public void DefinitionFunctionCallWord_CC() throws ParseException {
    DefinitionFunction_CC();
    jj_consume_token(FENHAO_TO);
  }

/** 赋�?�语�? */
  static final public void EvaluateWord_CC() throws ParseException {
    Token t;
    //id = <表达�?>;
        t = jj_consume_token(ID_TO);
    jj_consume_token(DENGHAO_TO);
    Expression_CC();
    jj_consume_token(FENHAO_TO);
        getVariableById(t,1);
  }

/** 返回语句 */
  static final public void ReturnWord_CC() throws ParseException {
    int flag=0;
    jj_consume_token(RETURN_TO);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LPARENTHESES_TO:
      jj_consume_token(LPARENTHESES_TO);
      Expression_CC();
        flag = 1;
      jj_consume_token(RPARENTHESES_TO);
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(FENHAO_TO);
        if(returnFlagType==0&&flag==1){
            ExError.ShowErrMsg(4,"This function must return null");
        }else if(returnFlagType==1&&flag==0){
            ExError.ShowErrMsg(4,"This function must return int");
        }
        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.RET,0,0);
        middleCodeList.add(item);
  }

/** 读语�? */
  static final public void ScanfWord_CC() throws ParseException {
    Token t;
    jj_consume_token(SCANF_TO);
    jj_consume_token(LPARENTHESES_TO);
    t = jj_consume_token(ID_TO);
    jj_consume_token(RPARENTHESES_TO);
    jj_consume_token(FENHAO_TO);
        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.RED,0,0);
        middleCodeList.add(item);
        getVariableById(t,1);
  }

/** 写语�? */
  static final public void PrintfWord_CC() throws ParseException {
    jj_consume_token(PRINTF_TO);
    jj_consume_token(LPARENTHESES_TO);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID_TO:
    case NUM_TO:
    case JIAHAO_TO:
    case JIANHAO_TO:
    case LPARENTHESES_TO:
      Expression_CC();
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    jj_consume_token(RPARENTHESES_TO);
    jj_consume_token(FENHAO_TO);
        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.WRT,0,0);
        middleCodeList.add(item);
  }

/** 表达�? */
  static final public void Expression_CC() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case JIAHAO_TO:
    case JIANHAO_TO:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case JIAHAO_TO:
        jj_consume_token(JIAHAO_TO);
        break;
      case JIANHAO_TO:
        jj_consume_token(JIANHAO_TO);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    Sum_CC();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case JIAHAO_TO:
      case JIANHAO_TO:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_4;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case JIAHAO_TO:
        t = jj_consume_token(JIAHAO_TO);
        break;
      case JIANHAO_TO:
        t = jj_consume_token(JIANHAO_TO);
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      Sum_CC();
        if(t.image.equals("+")){
            MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.ADD,0,0);
            middleCodeList.add(item);
        }else{
            MiddleCodeItem item1 = new MiddleCodeItem(MiddleCodeItem.CodeType.SUB,0,0);
            middleCodeList.add(item1);
        }
    }
  }

/** �? */
  static final public void Sum_CC() throws ParseException {
    Divisor_CC();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CHENGHAO_TO:
      case CHUHAO_TO:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CHENGHAO_TO:
        jj_consume_token(CHENGHAO_TO);
        Divisor_CC();
        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.MUL,0,0);
        middleCodeList.add(item);
        break;
      case CHUHAO_TO:
        jj_consume_token(CHUHAO_TO);
        Divisor_CC();
        MiddleCodeItem item1 = new MiddleCodeItem(MiddleCodeItem.CodeType.DIV,0,0);
        middleCodeList.add(item1);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

/** 因子 */
  static final public void Divisor_CC() throws ParseException {
    Token s;
    if (jj_2_6(2)) {
      DefinitionFunction_CC();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LPARENTHESES_TO:
        jj_consume_token(LPARENTHESES_TO);
        Expression_CC();
        jj_consume_token(RPARENTHESES_TO);
        break;
      case NUM_TO:
        s = jj_consume_token(NUM_TO);
        MiddleCodeItem item = new MiddleCodeItem(MiddleCodeItem.CodeType.LIT,0,Integer.parseInt(s.image));
        middleCodeList.add(item);
        break;
      default:
        jj_la1[13] = jj_gen;
        if (jj_2_7(2)) {
          s = jj_consume_token(ID_TO);
        getVariableById(s,0);
        } else {
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
  }

/** 自定义函数调�? */
  static final public void DefinitionFunction_CC() throws ParseException {
    Token t;
    //id '(' ')'
        t = jj_consume_token(ID_TO);
    jj_consume_token(LPARENTHESES_TO);
    jj_consume_token(RPARENTHESES_TO);
        getFunctionById(t);
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_3R_22() {
    if (jj_scan_token(ID_TO)) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_scan_token(ELSE_TO)) return true;
    if (jj_3R_9()) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_scan_token(PRINTF_TO)) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_scan_token(VOID_TO)) return true;
    if (jj_scan_token(ID_TO)) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_7()) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_6()) return true;
    return false;
  }

  static private boolean jj_3R_8() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_scan_token(SCANF_TO)) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_scan_token(IF_TO)) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    if (jj_scan_token(INT_TO)) return true;
    if (jj_scan_token(ID_TO)) return true;
    return false;
  }

  static private boolean jj_3R_7() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_11()) {
    jj_scanpos = xsp;
    if (jj_3R_12()) return true;
    }
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_6()) return true;
    return false;
  }

  static private boolean jj_3R_10() {
    if (jj_scan_token(ID_TO)) return true;
    if (jj_scan_token(LPARENTHESES_TO)) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_scan_token(WHILE_TO)) return true;
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3_7() {
    if (jj_scan_token(ID_TO)) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(RETURN_TO)) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_3R_22()) return true;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3R_6() {
    if (jj_scan_token(INT_TO)) return true;
    if (jj_scan_token(ID_TO)) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    if (jj_scan_token(LBRACE_TO)) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3_6() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_13()) {
    jj_scanpos = xsp;
    if (jj_3R_14()) {
    jj_scanpos = xsp;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompilerTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[14];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x10000,0xc0,0x827c20,0x800420,0x27800,0x2000000,0x20cc000,0xc0000,0xc0000,0xc0000,0xc0000,0x300000,0x300000,0x2008000,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[7];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Compiler(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compiler(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompilerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Compiler(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompilerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Compiler(CompilerTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(CompilerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 14; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[27];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 14; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 27; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 7; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
